<!DOCTYPE html>
<html lang="en">
<head>
<title>Terrain Field Foliage Farming Simulator 17 - PMC Farming</title>
<LINK href="../css.css" rel=stylesheet type="text/css">
<META name="description" content="Terrain Field Foliage Farming Simulator 17 - PMC Farming">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<?php include("../include/google-analytics.php"); ?>

</head>
<body>

<header>
<?php include("/var/www/include/ads.php"); ?>
<?php include("/var/www/include/header-start.php"); ?>
	<h1>Terrain Field Foliage Farming Simulator 17 - PMC Farming</h1>

<p>
Terrain Editing Tutorial: Terrain Field Foliage for Farming Simulator 17 (FS17) by PMC.
</p>
<?php include("/var/www/include/header-end.php"); ?>
</header>

<section>
<?php include("/var/www/include/section-start.php"); ?>
<?php include("/var/www/include/support.php"); ?>
	<h2>Terrain Field Foliage FS17</h2>

<p>
HOWTO create foliage for your fields.
</p>

<p>
Foliage or plant life, the first four channels (0 through 3) control the type of plant. The next row of channels (4 through 7) dictates that plant's growth state. In the third row of channels, only channel 8 has any effect. It defines whether the crop is in a windrow (a row of cut vegetation, ready to be baled or stored) or not.
</p>

<p>
Foliage channel settings for various crops:<br>
0, Wheat<br>
1, Grass<br>
2, Barley<br>
3, Sugar beet<br>
0 + 1, Rape (canola)<br>
0 + 2, Maize (corn)<br>
1 + 2, Dry grass<br>
1 + 2 + 3, Potato
</p>

<p>
Fortunately, <a href="terrain-giants-editor.php">Giants Editor FS17</a> helps you out a bit here. When choosing the crop you want from the Foliage Layer drop-down menu, it automatically sets the bitmask for the first four foliage channels.
</p>

<p>
2024-10-20T13:43:49Z special note; my memory is a bit hazy on FS17 editing dating back to 2018, but I don't think you technically need to create foliage to your fields, its automatically generated by <a href="terrain-field-definitions.php">field definitions</a>, so if you don't want, then there is no need to create foliage for fields, at least that's how it works in FS19 and FS22.
</p>

<?php include("/var/www/include/section-end.php"); ?>
</section>

<footer>
<?php include("/var/www/include/footer-start.php"); ?>
<?php include("../include/fs17-terrain-editing-tutorial-footer.php"); ?>
<?php include("/var/www/include/footer-end.php"); ?>
<?php include("/var/www/include/support.php"); ?>
<?php include("/var/www/include/w3-validator-logo.php"); ?>
</footer>

</body>
</html>
